# @Author: Nick Steele
# @Date:   13:38 Sep 05 2021
# @Last modified by:   Nick Steele
# @Last modified time: 23:29 Sep 08 2021

build:
	pio run

upload: up

up:
	pio run -t upload

test: FORCE
	@echo 'testing not yet implemented (sorry)'

FORCE:
